AllCops:
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
  DisplayCopNames: true
  NewCops: enable

  

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"
    
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Enabled: false