version: "3.9"

x-template: &rails
  build: .
  volumes:
    - .:/app
    - node-modules-volume:/app/node_modules
    - bundle-volume:/usr/local/bundle
  environment:
    REDIS_HOST: $REDIS_HOST
    REDIS_PORT: $REDIS_PORT
    REDIS_URL: $REDIS_URL
    FILEMAKER_HOST_SAFTA:  $FILEMAKER_HOST_SAFTA
    FILEMAKER_DB_SAFTA: $FILEMAKER_DB_SAFTA
    FILEMAKER_HOST_SUNLIFE:  $FILEMAKER_HOST_SUNLIFE
    FILEMAKER_DB_SUNLIFE: $FILEMAKER_DB_SUNLIFE
    CLARIS_ID: $CLARIS_ID
    CLARIS_PASS: $CLARIS_PASS
    BASIC_USER: $BASIC_USER
    BASIC_PASS: $BASIC_PASS

services:
  web:
    <<: *rails
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 8000:3000
    tty: true
    stdin_open: true
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-volume:/usr/loca/data
  sidekiq:
    <<: *rails
    command: bundle exec sidekiq
    depends_on:
      - redis
volumes:
  bundle-volume:
  node-modules-volume:
  redis-volume:
